SHOW DATABASES;
CREATE DATABASE PIZZA_DB;
USE PIZZA_DB;
SELECT *FROM PIZZA_SALES_EXCEL_FILE;


#TOTAL REVENUE GENERATED
SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES_EXCEL_FILE;

#AVERAGE ORDER VALUE
SELECT SUM(TOTAL_PRICE)/COUNT(DISTINCT ORDER_ID) AS AVG_ORDER_VALUE FROM PIZZA_SALES_EXCEL_FILE;

#TOTAL PIZZAS SOLD
SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALES_EXCEL_FILE;

#TOTAL ORDERS
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES_EXCEL_FILE;

#AVERAGE PIZZAS PER ORDER
SELECT SUM(QUANTITY)/COUNT(DISTINCT ORDER_ID) AS AVG_PIZZAS_PER_ORDER FROM PIZZA_SALES_EXCEL_FILE;


#PERCENTAGE OF SALES BY PIZZA CATEGORY
SELECT PIZZA_CATEGORY, CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) AS TOTAL_REVENUE,
CAST(SUM(TOTAL_PRICE)*100 / (SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES_EXCEL_FILE) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES_EXCEL_FILE
GROUP BY PIZZA_CATEGORY;

#PERCENTAGE OF SALES BY PIZZA SIZE
SELECT PIZZA_SIZE, CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) AS TOTAL_REVENUE,
CAST(SUM(TOTAL_PRICE)*100 / (SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES_EXCEL_FILE) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES_EXCEL_FILE
GROUP BY PIZZA_SIZE
ORDER BY PIZZA_SIZE;
 
 
#TOTAL PIZZAS SOLD BY PIZZA CATEGORY
SELECT PIZZA_CATEGORY, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD FROM PIZZA_SALES_EXCEL_FILE
GROUP BY PIZZA_CATEGORY
ORDER BY TOTAL_QUANTITY_SOLD DESC;

#TOP 5 PIZZAS BY REVENUE
SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES_EXCEL_FILE 
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE DESC LIMIT 5;

#BOTTOM 5 PIZZAS BY REVENUE
SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES_EXCEL_FILE 
GROUP BY PIZZA_NAME 
ORDER BY TOTAL_REVENUE LIMIT 5;

#TOP 5 PIZZAS BY QUANTITY
SELECT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALES_EXCEL_FILE 
GROUP BY PIZZA_NAME 
ORDER BY TOTAL_PIZZA_SOLD DESC LIMIT 5;

#BOTTOM 5 PIZZAS BY QUANTITY
SELECT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALES_EXCEL_FILE 
GROUP BY PIZZA_NAME 
ORDER BY TOTAL_PIZZA_SOLD LIMIT 5;

#TOP 5 PIZZAS BY TOTAL ORDERS
SELECT PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES_EXCEL_FILE 
GROUP BY PIZZA_NAME 
ORDER BY TOTAL_ORDERS DESC LIMIT 5;

#BOTTOM 5 PIZZAS BY TOTAL ORDERS
SELECT PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES_EXCEL_FILE 
GROUP BY PIZZA_NAME 
ORDER BY TOTAL_ORDERS LIMIT 5;





